name: Publish to Github Pages

on: [merge_group, workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm install --force
    - name: Build application
      run: npm run build
    - name: Publish to Github Pages
      run: npx gh-pages -d dist -u "${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
